Console.Clear();
int a = new Random().Next(1,100) ;
Console.Write("a = ");
Console.WriteLine(a);
int b = new Random().Next(1,100) ;
Console.Write("b = ");
Console.WriteLine(b);
int sum = a+b;
Console.Write("sum = ");
Console.WriteLine(sum);
